### ISSUE TITLE
No longer works with Java 8 JOSM

### ISSUE THREAD

**Issue by james2432** [kendzi/kendzi3d#59]
![image](https://cloud.githubusercontent.com/assets/498547/18435390/e02ef89a-78c0-11e6-82e4-55302c5a74cc.png)

**Comment by kendzi** [comment]
I just released new version 1.0.191 compiled on java 8. Please try it.

**Comment by james2432** [comment]
Same issue 
Status report has this to say:
`- W: Cannot lock cache directory. Will not use disk cache
- E: org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin kendzi3d. Cause: java.lang.reflect.InvocationTargetException. Cause: com.google.inject.CreationException: Guice creation errors:
- W: Disable plugin - Could not load plugin kendzi3d. Delete from preferences?`

**Comment by james2432** [comment]
I opened the java console for debugging and got this as output:
`INFO: loading plugin 'kendzi3d' (version 1.0.191)
copying file: /lib/jogl-2.3.2/jogl-all-2.3.2-natives-linux-armv6.jar exist skiping`

`copying file: /lib/jogl-2.3.2/jogl-all-2.3.2-natives-linux-armv6hf.jar exist skiping`

`copying file: /lib/jogl-2.3.2/jogl-all-2.3.2-natives-linux-amd64.jar exist skiping`

`copying file: /lib/jogl-2.3.2/jogl-all-2.3.2-natives-linux-i586.jar exist skiping`

`copying file: /lib/jogl-2.3.2/jogl-all-2.3.2-natives-macosx-universal.jar exist skiping`

`copying file: /lib/jogl-2.3.2/jogl-all-2.3.2-natives-solaris-amd64.jar exist skiping`

`copying file: /lib/jogl-2.3.2/jogl-all-2.3.2-natives-solaris-i586.jar exist skiping`

`copying file: /lib/jogl-2.3.2/jogl-all-2.3.2-natives-windows-amd64.jar exist skiping`

`copying file: /lib/jogl-2.3.2/jogl-all-2.3.2-natives-windows-i586.jar exist skiping`

`copying file: /lib/jogl-2.3.2/jogl-all-2.3.2.jar exist skiping`

`copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2-natives-linux-armv6.jar exist skiping`

`copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2-natives-linux-armv6hf.jar exist skiping`

`copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2-natives-linux-amd64.jar exist skiping`

`copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2-natives-linux-i586.jar exist skiping`

`copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2-natives-macosx-universal.jar exist skiping`

`copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2-natives-solaris-amd64.jar exist skiping`

`copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2-natives-solaris-i586.jar exist skiping`

`copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2-natives-windows-amd64.jar exist skiping`

`copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2-natives-windows-i586.jar exist skiping`

`copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2.jar exist skiping`

loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\jogl-all-2.3.2-natives-linux-armv6.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\jogl-all-2.3.2-natives-linux-armv6hf.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\jogl-all-2.3.2-natives-linux-amd64.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\jogl-all-2.3.2-natives-linux-i586.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\jogl-all-2.3.2-natives-macosx-universal.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\jogl-all-2.3.2-natives-solaris-amd64.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\jogl-all-2.3.2-natives-solaris-i586.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\jogl-all-2.3.2-natives-windows-amd64.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\jogl-all-2.3.2-natives-windows-i586.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\jogl-all-2.3.2.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\gluegen-rt-2.3.2-natives-linux-armv6.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\gluegen-rt-2.3.2-natives-linux-armv6hf.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\gluegen-rt-2.3.2-natives-linux-amd64.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\gluegen-rt-2.3.2-natives-linux-i586.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\gluegen-rt-2.3.2-natives-macosx-universal.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\gluegen-rt-2.3.2-natives-solaris-amd64.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\gluegen-rt-2.3.2-natives-solaris-i586.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\gluegen-rt-2.3.2-natives-windows-amd64.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\gluegen-rt-2.3.2-natives-windows-i586.jar
loading lib: C:\Users\cecce\AppData\Roaming\JOSM\plugins\jogl\lib\jogl-2.3.2\gluegen-rt-2.3.2.jar
Sep 13, 2016 8:04:46 AM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.lang.SecurityException: attempted to open sandboxed jar file:/C:/Users/cecce/AppData/Roaming/JOSM/plugins/jogl/lib/jogl-2.3.2/jogl-all-2.3.2.jar as a Trusted-Library
java.lang.SecurityException: attempted to open sandboxed jar file:/C:/Users/cecce/AppData/Roaming/JOSM/plugins/jogl/lib/jogl-2.3.2/jogl-all-2.3.2.jar as a Trusted-Library
	at com.sun.deploy.security.CPCallbackHandler$ParentElement.checkResource(Unknown Source)
	at com.sun.deploy.security.DeployURLClassPath$JarLoader.checkResource(Unknown Source)
	at com.sun.deploy.security.DeployURLClassPath$JarLoader.getResource(Unknown Source)
	at com.sun.deploy.security.DeployURLClassPath.getResource(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at com.sun.jnlp.JNLPClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.sun.jnlp.JNLPClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.sun.jnlp.JNLPClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at kendzi.josm.kendzi3d.module.Kendzi3dModule.configure(Kendzi3dModule.java:108)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at kendzi.josm.kendzi3d.Kendzi3DPlugin.<init>(Kendzi3DPlugin.java:82)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:327)
	at org.openstreetmap.josm.plugins.PluginHandler.loadPlugin(PluginHandler.java:706)
	at org.openstreetmap.josm.plugins.PluginHandler.loadPlugins(PluginHandler.java:758)
	at org.openstreetmap.josm.plugins.PluginHandler.loadLatePlugins(PluginHandler.java:797)
	at org.openstreetmap.josm.gui.MainApplication.loadLatePlugins(MainApplication.java:395)
	at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javaws.Launcher.executeApplication(Unknown Source)
	at com.sun.javaws.Launcher.executeMainClass(Unknown Source)
	at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
	at com.sun.javaws.Launcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Sep 13, 2016 8:04:46 AM org.openstreetmap.josm.Main error
SEVERE: org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin kendzi3d. Cause: java.lang.reflect.InvocationTargetException. Cause: com.google.inject.CreationException: Guice creation errors:

1) No implementation for kendzi.jogl.camera.ViewportPicker was bound.
  while locating kendzi.jogl.camera.ViewportPicker
    for parameter 0 at kendzi.kendzi3d.editor.selection.ObjectSelectionManager.<init>(ObjectSelectionManager.java:58)
  at kendzi.josm.kendzi3d.module.Kendzi3dModule.provideSelectionSynchronizeManager(Kendzi3dModule.java:244)

2) No implementation for kendzi.kendzi3d.editor.EditableObjectProvider was bound.
  while locating kendzi.kendzi3d.editor.EditableObjectProvider
    for parameter 1 at kendzi.kendzi3d.editor.selection.ObjectSelectionManager.<init>(ObjectSelectionManager.java:58)
  at kendzi.josm.kendzi3d.module.Kendzi3dModule.provideSelectionSynchronizeManager(Kendzi3dModule.java:244)

3) An exception was caught and reported. Message: attempted to open sandboxed jar file:/C:/Users/cecce/AppData/Roaming/JOSM/plugins/jogl/lib/jogl-2.3.2/jogl-all-2.3.2.jar as a Trusted-Library
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)

4) No implementation for kendzi.jogl.camera.Camera was bound.
  at kendzi.josm.kendzi3d.module.Kendzi3dModule.provideCameraLayer(Kendzi3dModule.java:192)

4 errors. Cause: java.lang.SecurityException: attempted to open sandboxed jar file:/C:/Users/cecce/AppData/Roaming/JOSM/plugins/jogl/lib/jogl-2.3.2/jogl-all-2.3.2.jar as a Trusted-Library
org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin kendzi3d
	at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:330)
	at org.openstreetmap.josm.plugins.PluginHandler.loadPlugin(PluginHandler.java:706)
	at org.openstreetmap.josm.plugins.PluginHandler.loadPlugins(PluginHandler.java:758)
	at org.openstreetmap.josm.plugins.PluginHandler.loadLatePlugins(PluginHandler.java:797)
	at org.openstreetmap.josm.gui.MainApplication.loadLatePlugins(MainApplication.java:395)
	at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javaws.Launcher.executeApplication(Unknown Source)
	at com.sun.javaws.Launcher.executeMainClass(Unknown Source)
	at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
	at com.sun.javaws.Launcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:327)
	... 14 more
Caused by: com.google.inject.CreationException: Guice creation errors:

1) No implementation for kendzi.jogl.camera.ViewportPicker was bound.
  while locating kendzi.jogl.camera.ViewportPicker
    for parameter 0 at kendzi.kendzi3d.editor.selection.ObjectSelectionManager.<init>(ObjectSelectionManager.java:58)
  at kendzi.josm.kendzi3d.module.Kendzi3dModule.provideSelectionSynchronizeManager(Kendzi3dModule.java:244)

2) No implementation for kendzi.kendzi3d.editor.EditableObjectProvider was bound.
  while locating kendzi.kendzi3d.editor.EditableObjectProvider
    for parameter 1 at kendzi.kendzi3d.editor.selection.ObjectSelectionManager.<init>(ObjectSelectionManager.java:58)
  at kendzi.josm.kendzi3d.module.Kendzi3dModule.provideSelectionSynchronizeManager(Kendzi3dModule.java:244)

3) An exception was caught and reported. Message: attempted to open sandboxed jar file:/C:/Users/cecce/AppData/Roaming/JOSM/plugins/jogl/lib/jogl-2.3.2/jogl-all-2.3.2.jar as a Trusted-Library
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)

4) No implementation for kendzi.jogl.camera.Camera was bound.
  at kendzi.josm.kendzi3d.module.Kendzi3dModule.provideCameraLayer(Kendzi3dModule.java:192)

4 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at kendzi.josm.kendzi3d.Kendzi3DPlugin.<init>(Kendzi3DPlugin.java:82)
	... 19 more
Caused by: java.lang.SecurityException: attempted to open sandboxed jar file:/C:/Users/cecce/AppData/Roaming/JOSM/plugins/jogl/lib/jogl-2.3.2/jogl-all-2.3.2.jar as a Trusted-Library
	at com.sun.deploy.security.CPCallbackHandler$ParentElement.checkResource(Unknown Source)
	at com.sun.deploy.security.DeployURLClassPath$JarLoader.checkResource(Unknown Source)
	at com.sun.deploy.security.DeployURLClassPath$JarLoader.getResource(Unknown Source)
	at com.sun.deploy.security.DeployURLClassPath.getResource(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at com.sun.jnlp.JNLPClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.sun.jnlp.JNLPClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.sun.jnlp.JNLPClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at kendzi.josm.kendzi3d.module.Kendzi3dModule.configure(Kendzi3dModule.java:108)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	... 23 more

Sep 13, 2016 8:04:46 AM org.openstreetmap.josm.Main warn
WARNING: Disable plugin - Could not load plugin kendzi3d. Delete from preferences?

**Comment by kendzi** [comment]
Looks like is failing to load jogl. Do you run it as Java Start?

**Comment by james2432** [comment]
Yes, I'm running it from the jnlp. The desktop version seems to work though(10966). is the jogl a signed package? Because since java 1.7 all unsigned packages are sandboxed and treated as melicious code

**Comment by kendzi** [comment]
Jogl package is provided by jogamp.org, and as I see it is not signed.

**Comment by don-vip** [comment]
Possible duplicate report: https://josm.openstreetmap.de/ticket/13635

**Comment by Mxdanger** [comment]
I get the same problem on my Mac running Java 8 Update 151

**Comment by DaveF63** [comment]
> Jogl package is provided by jogamp.org, and as I see it is not signed.

Hi
Windows 7, JOSM v14824, Java 8-201

First time using this plug-in.
I'm getting similar problems, but only with the Web Service version of JOSM:
"javaws.exe" https://josm.openstreetmap.de/download/josm.jnlp

Did anybody contact  jogamp to resovle the problem?

Using the downloaded version (josm-setup.exe) the plug-in loads correctly.
