### ISSUE TITLE
Error with load extension

### ISSUE THREAD

**Issue by jeawrong** [kendzi/kendzi3d#94]
When i started Josm I have this problem with Kendzi3d.

`2019-05-14 13:56:46.786 INFORMAZIONI: caricamento estensione 'kendzi3d' (versione 1.0.205)
2019-05-14 13:56:46.789 INFORMAZIONI: copying file: /lib/jogl-2.3.2/jogl-all-2.3.2-natives-linux-armv6.jar exist skiping

2019-05-14 13:56:46.789 INFORMAZIONI: copying file: /lib/jogl-2.3.2/jogl-all-2.3.2-natives-linux-armv6hf.jar exist skiping

2019-05-14 13:56:46.789 INFORMAZIONI: copying file: /lib/jogl-2.3.2/jogl-all-2.3.2-natives-linux-amd64.jar exist skiping

2019-05-14 13:56:46.790 INFORMAZIONI: copying file: /lib/jogl-2.3.2/jogl-all-2.3.2-natives-linux-i586.jar exist skiping

2019-05-14 13:56:46.790 INFORMAZIONI: copying file: /lib/jogl-2.3.2/jogl-all-2.3.2-natives-solaris-amd64.jar exist skiping

2019-05-14 13:56:46.790 INFORMAZIONI: copying file: /lib/jogl-2.3.2/jogl-all-2.3.2-natives-solaris-i586.jar exist skiping

2019-05-14 13:56:46.791 INFORMAZIONI: copying file: /lib/jogl-2.3.2/jogl-all-2.3.2.jar exist skiping

2019-05-14 13:56:46.791 INFORMAZIONI: copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2-natives-linux-armv6.jar exist skiping

2019-05-14 13:56:46.791 INFORMAZIONI: copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2-natives-linux-armv6hf.jar exist skiping

2019-05-14 13:56:46.792 INFORMAZIONI: copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2-natives-linux-amd64.jar exist skiping

2019-05-14 13:56:46.792 INFORMAZIONI: copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2-natives-linux-i586.jar exist skiping

2019-05-14 13:56:46.792 INFORMAZIONI: copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2-natives-solaris-amd64.jar exist skiping

2019-05-14 13:56:46.792 INFORMAZIONI: copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2-natives-solaris-i586.jar exist skiping

2019-05-14 13:56:46.793 INFORMAZIONI: copying file: /lib/jogl-2.3.2/gluegen-rt-2.3.2.jar exist skiping

2019-05-14 13:56:46.794 GRAVE: org.openstreetmap.josm.plugins.PluginException: È stato generato un errore dall'estensione kendzi3d. Causa: java.lang.reflect.InvocationTargetException. Causa: java.lang.NoSuchMethodError: org.openstreetmap.josm.tools.Utils.setObjectsAccessible([Ljava/lang/reflect/AccessibleObject;)V
org.openstreetmap.josm.plugins.PluginException: È stato generato un errore dall'estensione kendzi3d
        at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:365)
        at org.openstreetmap.josm.plugins.PluginHandler.loadPlugin(PluginHandler.java:804)
        at org.openstreetmap.josm.plugins.PluginHandler.loadPlugins(PluginHandler.java:890)
        at org.openstreetmap.josm.plugins.PluginHandler.loadLatePlugins(PluginHandler.java:933)
        at org.openstreetmap.josm.gui.MainApplication.loadLatePlugins(MainApplication.java:1143)
        at org.openstreetmap.josm.gui.MainApplication.mainJOSM(MainApplication.java:907)
        at org.openstreetmap.josm.gui.MainApplication$3.processArguments(MainApplication.java:277)
        at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:704)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:360)
        ... 7 more
Caused by: java.lang.NoSuchMethodError: org.openstreetmap.josm.tools.Utils.setObjectsAccessible([Ljava/lang/reflect/AccessibleObject;)V
        at kendzi.josm.jogl.JoglPlugin.doAddJarsToClassLoader(JoglPlugin.java:214)
        at kendzi.josm.jogl.JoglPlugin.addJarsToClassLoader(JoglPlugin.java:193)
        at kendzi.josm.jogl.JoglPlugin.addLibraryToClassPath(JoglPlugin.java:124)
        at kendzi.josm.jogl.JoglPlugin.addJoglToClassPath(JoglPlugin.java:55)
        at kendzi.josm.kendzi3d.Kendzi3DPlugin.<init>(Kendzi3DPlugin.java:80)
        ... 12 more

2019-05-14 13:56:46.834 AVVERTENZA: Disabilita estensione - Non è possibile caricare il plugin 'kendzi3d'. Cancellarlo dalle preferenze?

The choice is delete the plugin from the preferences of Josm. Any idea?

**Comment by jeawrong** [comment]
Solved, i have update the plugin Jogl and Kendzi3D work now :)

**Comment by kendzi** [comment]
Api was changed, but everything should work from josm version 14977.
